### ISSUE TITLE
Is it possible to remove the download button in the video player?

### ISSUE THREAD

**Issue by MTError** [webtor-io/embed-sdk-js#88]
![Screenshot 2022-09-12 at 14-28-00 fdhfdhfdhfhdfhdfhfhfdhfdhf](https://user-images.githubusercontent.com/42030811/189614092-5cb5b265-2468-44a1-9bd5-826b7f2d6889.png)

**Comment by vintikzzz** [comment]
no, it generates traffic to my site...
